pair/crud/urls.py
from django.urls import path
from . import views

app_name = "crud"

urlpatterns = [
    path("", views.index, name="index"),
    path("create/", views.create, name="create"),
    path("created_at/", views.created_at, name="created_at"),
    path("detail/<int:review_pk>", views.detail, name="detail"),
    path("delete/<int:review_pk>", views.delete, name="delete"),
    path("update/<int:review_pk>", views.update, name="update"),
    path("updated/<int:review_pk>", views.updated, name="updated"),    
]

pair/pair/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("crud.urls")),
]

pair/crud/models.py
from django.db import models

# Create your models here.


class Review(models.Model):
    title = models.CharField(max_length=80)
    content = models.TextField(null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

pair/crud/views.py
from django.shortcuts import render, redirect
from .models import Review
import datetime

# Create your views here.
def index(request):
    reviews = Review.objects.all()
    context = {
        "reviews": reviews,
    }
    return render(request, "crud/index.html", context)


def create(request):
    return render(request, "crud/create.html")


def created_at(request):
    title = request.GET.get("title")
    content = request.GET.get("content")
    Review.objects.create(
        title=title,
        content=content,
    )
    return redirect("crud:index")


def detail(request, review_pk):
    review = Review.objects.get(pk=review_pk)
    context = {
        "review": review,
    }
    return render(request, "crud/detail.html", context)


def delete(request, review_pk):
    Review.objects.get(pk=review_pk).delete()
    return redirect("crud:index")


def update(request, review_pk):
    review = Review.objects.get(pk=review_pk)
    context = {
        "review": review,
    }
    return render(request, "crud/update.html", context)


def updated(request, review_pk):
    review = Review.objects.get(pk=review_pk)
    title_updated = request.GET.get("title_updated")
    content_updated = request.GET.get("content_updated")
    review.title = title_updated
    review.content = content_updated
    review.save()
    return redirect("crud:index")

pair/crud/templates/crud/create.html
{% extends 'base.html' %}

{% block content %}
<form action="{% url 'crud:created_at' %}">
    <div class="mb-3">
        <label for="exampleFormControlInput1" class="form-label">제목</label>
        <input type="text" class="form-control" name="title" placeholder="제목을 입력해주세요.">
    </div>
    <div class="mb-3">
        <label for="exampleFormControlTextarea1" class="form-label">내용</label>
        <input type="text" class="form-control" name="content" rows=" 3">
    </div>
    <div class="col-1">
        <input class="btn btn-primary btn-sm" type="submit" value="제출">
    </div>
</form>
<a href="{% url 'crud:index' %}">홈</a>
{% endblock %}

pair/crud/templates/crud/detail.html
{% extends 'base.html' %}

{% block content %}
<section class="container m-3 d-flex justify-content-center flex-column">
    <a class="btn border-white col-2 fw-bolder btn-lg" href="{% url 'crud:index' %}"> HOME</a>
    <table class="table-secondary table-bordered">
        <thead>
            <tr class="align-middle text-bg-dark">
                <th class="p-2" style="font-size: 2rem;">{{ review.title }}</th>
            </tr>
            <tr style="background: #D8D8D8;">
                <th class="p-2 small">num.{{ review.pk }}</th>
            </tr>
            <tr style="background: #D8D8D8;">
                <th class="p-2 small">Date created : {{ review.updated_at }}</th>
            </tr>
        </thead>
        <tbody>

            <tr>
                <th class="p-3">{{ review.content }}</th>
            </tr>
        </tbody>
    </table>
    <div class="d-flex justify-content-end">
        <a class="btn btn-info m-1 text-white" href="{% url 'crud:update' review.pk %}">수정</a>
        <a class="btn btn-danger m-1" href="{% url 'crud:delete' review.pk %}">삭제</a>
    </div>
</section>
{% endblock %}

pair/crud/templates/crud/index.html
{% extends 'base.html' %}

{% block content %}
<section class="container">
    <a type="button" class="btn btn-dark" href="{% url 'crud:create' %}"
        style="--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .75rem;">
        리뷰 작성
    </a>
    <table class="table my-2">
        <thead class="text-bg-dark">
            <tr>
                <th>글번호</th>
                <th>제목</th>
                <th>작성시간</th>
            </tr>
        </thead>
        <tbody>
            {% for review in reviews %}
            <tr>
                <td><a href="{% url 'crud:detail' review.pk %}">{{ review.pk }}</a></td>
                <td>{{ review.title }}</td>
                <td>{{ review.created_at }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

</section>
{% endblock %}

pair/crud/templates/crud/update.html
{% extends 'base.html' %}

{% block content %}
<form action="{% url 'crud:updated' review.pk %}">
  <div class="mb-3">
      <label for="exampleFormControlInput1" class="form-label">제목</label>
      <input type="text" class="form-control" name="title_updated" value="{{ review.title }}">
  </div>
  <div class="mb-3">
      <label for="exampleFormControlTextarea1" class="form-label">내용</label>
      <input type="text" class="form-control" name="content_updated" value="{{ review.content }}">
  </div>
  <div class="col-1">
      <input class="btn btn-primary btn-sm" type="submit" value="제출">
  </div>
</form>
{% endblock %}

pair/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
  <link rel="shortcut icon" type="image/x-icon" href="{% static 'images/smiley.ico'%}">
  <title>MV | Review</title>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- Bootstrap CSS v5.2.0-beta1 -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css"
    integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
</head>
<body>
  <header>
    <!-- place navbar here -->
  </header>
  <main>
    {% block content %}
    {% endblock %}
  </main>
  <footer>
    <!-- place footer here -->
  </footer>
  <!-- Bootstrap JavaScript Libraries -->
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js"
    integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk" crossorigin="anonymous">
  </script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.min.js"
    integrity="sha384-ODmDIVzN+pFdexxHEHFBQH3/9/vQ9uori45z4JjnFsRydbmQbmL5t1tQ0culUzyK" crossorigin="anonymous">
  </script>
</body>
</html>